title: "Operating Systems 2021/2022-1"
author: "Keyza Asyadda Ramadhan M."
url: "https://keyza-asyadda.github.io/os212"
repo: "https://github.com/Keyza-asyadda/os212"
course-name: "Operating Systems"
